name: CI Build auth

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - '**/build-auth.yml'
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: [ruoyi-auth]
        image-version: [v1.0]


    steps:
    - name: Checkout
      uses: actions/checkout@master
   
    - name: Build jar 
      run: |
        sudo mvn clean 
        sudo mvn package
        
    - name: Copy jar 
      run: |
        cp -rf .\ruoyi-auth\target\ruoyi-auth.jar docker\target\
      
      
    - name: docker build
      run: |
        sudo docker build -t ${{ matrix.image-name }}:${{ matrix.image-version }} .

      
    - name: push aliyun
      env:
        aliyun_username: ${{ secrets.Aliyun_Username }}
        aliyun_password: ${{ secrets.Aliyun_Password }}
      run: |
        sudo docker login --username=${aliyun_username} registry.cn-shenzhen.aliyuncs.com --password=${{ secrets.aliyun_password }}
        sudo docker tag ${{ matrix.image-name }}:${{ matrix.image-version }} registry.cn-shenzhen.aliyuncs.com/devdev/${{ matrix.image-name }}:${{ matrix.image-version }}
        sudo docker push registry.cn-shenzhen.aliyuncs.com/devdev/${{ matrix.image-name }}:${{ matrix.image-version }}
