name: CI Build Ruoyi-gateway

on:
  push:
    branches: 
      - master
    paths:
      - '**/build-gateway.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: [ruoyi-gateway]
        image-version: [v2.6]


    steps:
    - name: Checkout
      uses: actions/checkout@master
   
    - name: Build jar 
      run: |
        sudo mvn clean 
        sudo mvn package
        
    - name: Copy jar 
      run: |
        cp -rf ./ruoyi-gateway/target/ruoyi-gateway.jar ./docker/target/
      
    - name: docker build
      run: |
        cd docker/
        sudo docker build -f  DockerfileGateway -t ${{ matrix.image-name }}:${{ matrix.image-version }}  .
  
    - name: push aliyun
      env:
        aliyun_username: ${{ secrets.ALIYUN_USERNAME}}
        aliyun_password: ${{ secrets.ALIYUN_PASSWORD}}
      run: |
        sudo docker images
        sudo docker tag ${{ matrix.image-name }}:${{ matrix.image-version }}  registry.cn-shenzhen.aliyuncs.com/devdev/${{ matrix.image-name }}:${{ matrix.image-version }}
        sudo docker images
        sudo echo "${aliyun_password}" | docker login --username=${aliyun_username} registry.cn-shenzhen.aliyuncs.com --password-stdin 
        docker push registry.cn-shenzhen.aliyuncs.com/devdev/${{ matrix.image-name }}:${{ matrix.image-version }}
