name: CI Build Ruoyi-auth

on:
  push:
    branches: 
      - master
    paths:
      - '**/build-auth.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: [ruoyi-auth]
        image-version: [v1.0]


    steps:
    
   
    - name: push aliyun
      env:
        aliyun_username: ${{ secrets.ALIYUN_USERNAME}}
        aliyun_password: ${{ secrets.ALIYUN_PASSWORD}}
      run: |
        sudo docker images
        sudo docker tag ubuntu:18.04  registry.cn-shenzhen.aliyuncs.com/devdev/${{ matrix.image-name }}:${{ matrix.image-version }}
        sudo docker images
        sudo echo "${aliyun_password}" | docker login --username=${aliyun_username} registry.cn-shenzhen.aliyuncs.com --password-stdin 
        docker push registry.cn-shenzhen.aliyuncs.com/devdev/ruoyi-auth:v1.0
