name: CI Build Ruoyi-ui

on:
  push:
    branches: 
      - master
    paths:
      - '**/build-ui.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: [ruoyi-ui]
        image-version: [v1.0]


    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 10
        registry-url: https://registry.npmjs.org/
   
    - name: Build install 
      run: |
        cd ./ruoyi-ui
        sudo npm install 
        sudo npm build:prod
        ls
        cd ..
        
    - name: Copy html 
      run: |
        cp -rf ./ruoyi-ui/dest/ ./docker/nginx/html/
        ls ./docker/nginx/html/dest
      
    - name: docker build
      run: |
        cd docker/nginx
        sudo docker build -t ${{ matrix.image-name }}:${{ matrix.image-version }} .
  
    - name: push aliyun
      env:
        aliyun_username: ${{ secrets.ALIYUN_USERNAME}}
        aliyun_password: ${{ secrets.ALIYUN_PASSWORD}}
      run: |
        sudo docker images
        sudo docker tag ${{ matrix.image-name }}:${{ matrix.image-version }}  registry.cn-shenzhen.aliyuncs.com/devdev/${{ matrix.image-name }}:${{ matrix.image-version }}
        sudo docker images
        sudo echo "${aliyun_password}" | docker login --username=${aliyun_username} registry.cn-shenzhen.aliyuncs.com --password-stdin 
        docker push registry.cn-shenzhen.aliyuncs.com/devdev/${{ matrix.image-name }}:${{ matrix.image-version }}
